# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

# install minimal packages for debian slim images
RUN apt-get update && \
    apt-get install -y python sudo bash ca-certificates iproute2 systemd systemd-sysv python-pip && \
    apt-get clean

EXPOSE 8088/tcp
EXPOSE 5000/tcp
EXPOSE 8081/tcp